### ISSUE TITLE
『携带尽可能多的大发』选项没考虑到增益上限

### ISSUE THREAD

**Issue by wafer-li** [poooi/poi-plugin-ezexped#25]
事实上 4 个大发增益就已经达到上限了，似乎该选项没有考虑到这点

**Comment by Javran** [comment]
@wafer-li 可否提供具体例子:什么情况下,已经携带了足够数量的大发,但是插件中那个检查却未通过?

**Comment by wafer-li** [comment]
远征全发出去了，维护之后再看看吧， 可能是我看错了。

2017-09-29 10:58 GMT+09:00 Javran Cheng <notifications@github.com>:

**Comment by Javran** [comment]
@wafer-li 由于我确实从来没解释过这个判断具体是怎么回事(因为实在有点麻烦而且个人感觉没必要说这么详细), 就在这里解释下好了,对应的代码是:
https://github.com/poooi/poi-plugin-ezexped/blob/07ecd726edcbe1e46c52c55fbbf0a67a2a677734/structs/ereq/fill-dlc.es

判断逻辑是:

- 若不存在闲置的 "特大发动艇" 或者 "大发动艇",检查通过.
    - 所谓闲置,就是未被任何当前舰队中的舰娘装备的
    - 八九式战车和内火艇因为收益低不在考虑范围内
- 若不考虑改修 / 特大发额外收益时, 已达到 20%的收益系数,检查通过
- 队伍中不存在可以装备大发的舰娘,检查通过
- 队伍中可以装备大发的舰娘在排除运输桶和大发系装备后,还有额外的能装备大发的格子.则检查未通过,否则检查通过.

所以你说的4个大发达到上限,已经考虑在内了,若有反例欢迎指出.

**Comment by wafer-li** [comment]
![image](https://user-images.githubusercontent.com/12459199/31022837-012aeda6-a575-11e7-9467-569bbf4c3fb5.png)

如月的是三个大发，千代田是 『特大发 + 11 战队』

**Comment by wafer-li** [comment]
编成日记 导出的代码，应该会有点帮助？
```
[[[107,[63,10],[41,41,230],[],[]],[435,[93,13],[68,68,68],[],[]],[106,[46,10],[],[],[]],[240,[63,12],[75,75,75],[],[]],[316,[64,17],[75,75,75],[],[]],[309,[66,14],[75,75,75],[],[]]]]
```

**Comment by Javran** [comment]
@wafer-li 11连队没有任何远征收益上的,或者改修星数的影响. 

[特大発動艇＋戦車第11連隊](http://wikiwiki.jp/kancolle/?%C6%C3%C2%E7%C8%AF%C6%B0%C4%FA%A1%DC%C0%EF%BC%D6%C2%E811%CF%A2%C2%E2)

> ただしあちらと異なり遠征での資源増加効果は無い。

**Comment by gnattu** [comment]
@Javran 并没有，这个和特大发同样有比例

**Comment by wafer-li** [comment]
@Javran 我感觉是不是都无所谓：

- 如果不是，那么从图上来看，已经满足无闲置大发
- 如果是，那么这个东西都装上去了，满足 4 大发。

**Comment by Javran** [comment]
@wafer-li 有没有其他未在任何舰队中的舰娘装备了大发?

**Comment by wafer-li** [comment]
@Javran 有的。我是几个大发 DD 轮着用的。

**Comment by wafer-li** [comment]
但是，我换个远征，即使只有 3 个大发，也通过了检查。

![image](https://user-images.githubusercontent.com/12459199/31023804-fc0ff0d4-a577-11e7-8eee-5a487e506ac7.png)

**Comment by Javran** [comment]
@wafer-li 那就没错了,把那些大发挪过来替换特大发11连队就好了. 上面说过了11连队没有收益加成的.

然后你这个截图,之所以能通过检查是因为只有如月能带大发.

**Comment by wafer-li** [comment]
好的，明白了。

**Comment by Javran** [comment]
@wafer-li 了解,我大概会在以后版本说明一下11连队的问题.
