### ISSUE TITLE
在poi 10.0.0的Dark主题下，是否满足远征条件的高亮失效

### ISSUE THREAD

**Issue by Sunev** [poooi/poi-plugin-ezexped#29]
如图，Dark主题下不能直观区分
![image](https://user-images.githubusercontent.com/12387091/50603463-843edf00-0ef5-11e9-9ecb-4071baf5a15a.png)
顺便，Light主题下正常
![image](https://user-images.githubusercontent.com/12387091/50603493-9d479000-0ef5-11e9-90f3-c6af386f877f.png)

**Comment by Javran** [comment]
已知问题. 会抽空调整.
