### ISSUE TITLE
点开远征列表时所有远征按钮都叠在Row1/Col1上

### ISSUE THREAD

**Issue by h5nc** [poooi/poi-plugin-ezexped#34]
https://github.com/poooi/poi-plugin-ezexped/compare/master...h5nc:patch-1

**Comment by h5nc** [comment]
ExpeditionButton中的ThisToolTip貌似实际上并不是每次使用此控件都重新产生一个style class而是用最开始创建的gridRow:1/gridCol:1的class。
导致所有远征按钮叠在一起，目前看起来就像列表中只有46号远征一样

https://bbs.nga.cn/read.php?pid=419281140&opt=128
这里2440楼也有人提到过。

刚学electron，先把compare放在这里期待有人能pre-review一下

**Comment by Javran** [comment]
個人目前暫時做法是用electron 8. 這代碼如果本地測試可用發PR唄.

**Comment by Javran** [comment]
1.7.6 剛發佈. 如果還有問題再開本issue.
