### ISSUE TITLE
远征B6条件缺少

### ISSUE THREAD

**Issue by KIrayamoto** [poooi/poi-plugin-ezexped#39]
插件只检查了1CL 5DD是否满足，但是CL必须为旗舰这一条件没有

**Comment by jimmyzzxhlh** [comment]
https://github.com/poooi/poi-plugin-ezexped/pull/40 @Javran 可以看一下吗，谢谢

**Comment by Javran** [comment]
@jimmyzzxhlh already in-line commented in the PR

**Comment by jimmyzzxhlh** [comment]
> @jimmyzzxhlh already in-line commented in the PR

Did you publish it? I don't see any comments added yet.
