### ISSUE TITLE
Reducer shouldn't throw error

### ISSUE THREAD

**Issue by KochiyaOcean** [poooi/poi-plugin-ezexped#4]
Throw error in reducer will make the full action stopped working. Use `console.error` instead.

**Comment by Javran** [comment]
there are two fixes and I actually plan to both:

- the only `throw` possible through user side usages is the one in https://github.com/poooi/poi-plugin-ezexped/blob/b149a0aa13e6a7634d1de95dd0a33ccaec40590d/estype.es#L59-L65, which I'm gonna replace it with a `console.error`
- translation missing for ja-JP and ko-KR, I'll use copies of en version as a placeholder, it's not the best solution but should fix the problem without getting too much into how `i18n-2` works.

additionally, after a second thought, I was using `throw` statements to make better error messages and capture problems as early as possible, but then the same can also be said for using `console.error`, so I'm also going to remove all uses of `throw`, but this is the next stage and might take time.
