### ISSUE TITLE
Issue with new GS checkers

### ISSUE THREAD

**Issue by Javran** [poooi/poi-plugin-ezexped#45]
New GS checkers introduced in https://github.com/poooi/poi-plugin-ezexped/pull/43 needs some extra work to make it actually work, namely all checking should be done inside `./structs/ereq` - mutating props in render function violates React's data model thus cannot work reliably. For now `./exped-reqs/great-success.es` is reverted until this can be addressed.

**Comment by Javran** [comment]
@OniJAM Let me know if you have time and I can assign this to you - I could look into it but no promise on timing.

**Comment by OniJAM** [comment]
So here's the thing: GS rate checkers are done in `./structs/ereq` for normal-type and flagship-type expeditions and didn't have bugs for now, you can see there are tons of bugs founded these days in drum-type expeditions.

Different drum-type expeditions have different requirements on the amount of drums, but in `performStage1`, checkers don't actually know the expedID and how many drums are need for GS, in this case, I can't calculate the correct GS rate in one function. (btw, setting different functions for every drum-type expeditions is the fastest way to solve this issue but it is duplicated) I was setting `{min: drum requirement for success, max: drum requirement for GS}` to make things done in `./ui` but it is removed in [901eb15](https://github.com/poooi/poi-plugin-ezexped/commit/901eb1591ef3cf8984e2bd1bfb13d27d8e02f7ea). So I'm working on the mentioned dump and duplicated way to make checkers work and we may have time to look for a better way.

**Comment by Javran** [comment]
I removed some in [901eb15](https://github.com/poooi/poi-plugin-ezexped/commit/901eb1591ef3cf8984e2bd1bfb13d27d8e02f7ea) since there are not used anywhere in the body of `prepare` so I wasn't sure why they were there in the first place. Now I see what you want to do, feel free to add them back. Nothing should be done in `./ui` - it's merely the "viewer" part of the plugin, which are not supposed to make any mutations to props.

Few notes about related parts in the codebase, see if those help: there are `make` to pack arguments and `prepare` will have access to them as EReq objects.

Example: https://github.com/poooi/poi-plugin-ezexped/blob/6c2678c8ae5d48ecbcf06dd173f4bc5227f678c6/structs/ereq/total-asw.es#L15-L17 - the body of `prepare` function is where all checking logic should go (see comments in `structs/ereq/index.es` for detail).

The name `prepare` is confusing since it's a curried function but it is supposed to do all the heavy lifting despite its name, it's effectively called like this: `prepare(<EReq>)(<pState>)(Fleet,Extra)` - so we do have all things available to us in the body of this function - if necessary you can play with selectors a bit to pass down info you need (selectors/exped-reqs.es)

Since expedition id are mostly static, you could try to simply pass it as arguments to `make`, all the other stuff that require knowing current fleet, can be computed and attached to the `Extra` part passed in result stage (where Fleet and Extra) are passed as final arguments to `prepare` - you might need to play with selectors a bit.

**Comment by Javran** [comment]
Created `gs` branch, with `great-sucess.es` recovered - you can use that as PR target branch.
