### ISSUE TITLE
能否增加用于隐藏第一舰队的选项？

### ISSUE THREAD

**Issue by EdiTurn** [poooi/poi-plugin-ezexped#7]
第一舰队不能派出远征，就个人而言也从来没有用第一舰队来检查过远征的编成。
因此，能否考虑增加一个选项，在易及远征插件界面中隐藏第一舰队？

**Comment by Javran** [comment]
了解,会考虑加一下.

**Comment by Javran** [comment]
这个功能已实现,等新版本更新.
